import RNFS from 'react-native-fs';
import PDFLib from 'react-native-pdf-lib';

const generatePDFReport = async (image, analysisResult) => {
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const fileName = `SnapProof_Report_${timestamp}.pdf`;
    const path = `${RNFS.DocumentDirectoryPath}/${fileName}`;

    // Create PDF document
    const pdfDoc = await PDFLib.createDocument(path);
    const page = await pdfDoc.addPage(PDFLib.PageSizes.A4);

    // Add title
    await page.drawText('SnapProof Forensic Analysis Report', {
      x: 50,
      y: 750,
      fontSize: 24,
      color: '#2c3e50',
    });

    // Add timestamp
    await page.drawText(`Generated: ${new Date().toLocaleString()}`, {
      x: 50,
      y: 720,
      fontSize: 12,
      color: '#7f8c8d',
    });

    // Add risk assessment section
    await page.drawText('RISK ASSESSMENT', {
      x: 50,
      y: 680,
      fontSize: 16,
      color: '#2c3e50',
      bold: true,
    });

    await page.drawText(`Tampering Risk: ${analysisResult.tamperingRisk}`, {
      x: 50,
      y: 650,
      fontSize: 14,
      color: analysisResult.tamperingRisk === 'High' ? '#e74c3c' : 
             analysisResult.tamperingRisk === 'Medium' ? '#f39c12' : '#27ae60',
    });

    // Add technical analysis section
    await page.drawText('TECHNICAL ANALYSIS', {
      x: 50,
      y: 600,
      fontSize: 16,
      color: '#2c3e50',
      bold: true,
    });

    await page.drawText(`Error Level Analysis Score: ${analysisResult.elaScore}%`, {
      x: 50,
      y: 570,
      fontSize: 12,
      color: '#2c3e50',
    });

    await page.drawText(`Metadata Consistency: ${analysisResult.metadataConsistency}`, {
      x: 50,
      y: 550,
      fontSize: 12,
      color: '#2c3e50',
    });

    await page.drawText(`Compression Analysis: ${analysisResult.compressionAnalysis}`, {
      x: 50,
      y: 530,
      fontSize: 12,
      color: '#2c3e50',
    });

    // Add tampered regions if any
    if (analysisResult.tamperedRegions && analysisResult.tamperedRegions.length > 0) {
      await page.drawText('SUSPICIOUS REGIONS DETECTED:', {
        x: 50,
        y: 500,
        fontSize: 14,
        color: '#e74c3c',
        bold: true,
      });

      let yPos = 470;
      for (let i = 0; i < analysisResult.tamperedRegions.length; i++) {
        const region = analysisResult.tamperedRegions[i];
        await page.drawText(`${i + 1}. ${region.type} (Confidence: ${region.confidence}%)`, {
          x: 50,
          y: yPos,
          fontSize: 11,
          color: '#2c3e50',
        });
        yPos -= 20;
      }
    }

    // Add legal assessment section
    await page.drawText('LEGAL ASSESSMENT', {
      x: 50,
      y: 400,
      fontSize: 16,
      color: '#2c3e50',
      bold: true,
    });

    if (analysisResult.legalViolations.length > 0) {
      let yPos = 370;
      for (let i = 0; i < analysisResult.legalViolations.length; i++) {
        const violation = analysisResult.legalViolations[i];
        await page.drawText(`${i + 1}. ${violation.section}`, {
          x: 50,
          y: yPos,
          fontSize: 12,
          color: '#e74c3c',
          bold: true,
        });
        await page.drawText(violation.description, {
          x: 50,
          y: yPos - 20,
          fontSize: 10,
          color: '#2c3e50',
        });
        yPos -= 50;
      }
    } else {
      await page.drawText('No specific legal violations detected', {
        x: 50,
        y: 370,
        fontSize: 12,
        color: '#27ae60',
      });
    }

    // Add summary section
    await page.drawText('FORENSIC SUMMARY', {
      x: 50,
      y: 200,
      fontSize: 16,
      color: '#2c3e50',
      bold: true,
    });

    // Word wrap for long summary text
    const summaryWords = analysisResult.summary.split(' ');
    let currentLine = '';
    let yPos = 170;
    const maxCharsPerLine = 60;

    for (const word of summaryWords) {
      if ((currentLine + word).length <= maxCharsPerLine) {
        currentLine += (currentLine ? ' ' : '') + word;
      } else {
        await page.drawText(currentLine, {
          x: 50,
          y: yPos,
          fontSize: 10,
          color: '#2c3e50',
        });
        currentLine = word;
        yPos -= 15;
      }
    }

    if (currentLine) {
      await page.drawText(currentLine, {
        x: 50,
        y: yPos,
        fontSize: 10,
        color: '#2c3e50',
      });
    }

    // Add disclaimer
    await page.drawText('This report is generated by AI analysis and should be verified by qualified forensic experts.', {
      x: 50,
      y: 80,
      fontSize: 8,
      color: '#95a5a6',
    });

    await pdfDoc.write();

    return path;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF report');
  }
};

const shareReport = async (image, analysisResult) => {
  try {
    const shareText = `
SnapProof Forensic Analysis Report
=================================

Risk Level: ${analysisResult.tamperingRisk}
Analysis Date: ${new Date().toLocaleString()}

Technical Findings:
- Error Level Analysis: ${analysisResult.elaScore}% anomalies
- Metadata: ${analysisResult.metadataConsistency}
- Compression: ${analysisResult.compressionAnalysis}

Legal Assessment:
${analysisResult.legalViolations.map(v => `- ${v.section}: ${v.description}`).join('\n')}

Summary: ${analysisResult.summary}

Generated by SnapProof - AI Fake Image Detector
    `;

    return shareText.trim();
  } catch (error) {
    console.error('Share report error:', error);
    throw new Error('Failed to prepare share content');
  }
};

export {
  generatePDFReport,
  shareReport,
};
